// Bilingual content dictionary for FIGHT4 Foundation
// Every string the user sees lives here. Translations edited in place.

export type Locale = 'en' | 'es';

export const content = {
  en: {
    nav: {
      tagline: 'By the people, for the people.',
      resources: 'Resources',
      quickGuides: 'Quick Guides',
      story: 'Our Story',
      movement: '#WhatDoYouFight4',
      ask: 'Ask F4',
    },
    trustBar: {
      verified: 'Every resource personally verified by young adults who have been in treatment',
      updated: 'Updated monthly',
      disclaimer: 'Medical disclaimer',
    },
    hero: {
      eyebrow: 'The FIGHT4 Foundation',
      lede: 'By the people, for the people.',
      h1Line1: 'By young adults',
      h1Line1Mark: 'with cancer.',
      h1Line2: 'For young adults',
      h1Line2Mark: 'with cancer.',
      sub: "Financial aid. Support groups. Free experiences. Connections to the organizations that can actually help. Every resource on FIGHT4 is personally reviewed by young adults who've been through treatment — because we've used most of them ourselves.",
      ctaPrimary: 'Get matched to resources',
      ctaSecondary: 'Browse the library',
    },
    stats: {
      raised: { num: '$90K', label: 'Raised for blood cancer research via LLS' },
      partners: { num: '5', label: 'Partner organizations in the YA cancer space' },
      vetted: { num: '100%', label: "Resources vetted by young adults who've been there" },
    },
    founder: {
      tag: 'Founder',
      quote: "\"For seven months doctors told me it was meningitis. When I was finally diagnosed — Splenic Marginal Zone Non-Hodgkin's Lymphoma, one month before my 23rd birthday — sorting through resources while in treatment was its own kind of exhausting. FIGHT4 is what I wish I had then.\"",
      name: 'Natalia Menéndez',
      role: 'Founder · SMZL survivor · LLS Visionaries of the Year candidate · Personally reviews every resource',
      closing: 'By the people, for the people.',
    },
    partners: {
      label: 'Connected to the organizations young adults with cancer actually need',
      disclaimer: 'Logos shown with permission. Organizations listed are not formal sponsors of FIGHT4 Foundation.',
    },
    pillars: {
      title: 'Four pillars, one mission: no one fights alone.',
      subtitle: 'Our framework for what we cover, what we vet, and how we support young adults worldwide.',
      items: [
        { num: '01 / NAVIGATING INFORMATION', title: 'Cut through the noise', body: "Combing through available resources can be overwhelming. We do the work of finding, summarizing, and organizing — so you don't have to." },
        { num: '02 / EDUCATION', title: 'Break the stigma', body: 'Conversations about topics that feel taboo or difficult are how we build understanding, community, and courage in young adults facing cancer.' },
        { num: '03 / RESOURCE HUB', title: 'One centralized library', body: 'Financial aid, support groups, free experiences, connections to major organizations — all in one place, filterable by your situation.' },
        { num: '04 / GLOBAL NETWORK', title: 'No matter where you are', body: "Cancer doesn't stop at borders. Our library is curated with an international mindset, connecting young adults to resources worldwide." },
      ],
    },
    disclaimer: {
      heading: 'Medical disclaimer.',
      body: 'FIGHT4 summarizes publicly available information from trusted sources like hospitals, healthcare providers, and non-profits. While we aim for accuracy, please verify details with healthcare professionals. We do not cover every resource available and do not endorse any specific organizations. External links are for convenience only. This resource is not a substitute for professional medical care — always consult your medical team and support groups for personalized advice.',
    },
    footer: {
      brandLine1: 'By the people,',
      brandLine2: 'for the people.',
      tagline: 'FIGHT4 Foundation — built by young adults with cancer, for young adults with cancer. No one fights alone.',
      colResources: 'Resources',
      colFoundation: 'Foundation',
      colTrust: 'Trust',
      copyright: '© 2026 FIGHT4 Foundation',
      reviewedBy: 'Every resource personally reviewed by Natalia Menéndez, NHL survivor.',
    },
    about: {
      eyebrow: 'Our Story',
      h1: "For seven months, doctors told me it was meningitis.",
      lede: "On the other end of six lumbar punctures, multiple biopsies, and ER visits I'd rather forget — I was finally diagnosed with Splenic Marginal Zone Non-Hodgkin's Lymphoma, one month before my 23rd birthday.",
      body1: "I was at risk for stroke, had severe cognitive symptoms, debilitating migraines, and half of my body would go numb. For months I saw infectious disease specialists, neurologists, and oncologists who couldn't find it.",
      body2: "The cancer had gotten into my central nervous system. The average age at diagnosis for SMZL is 65–70 years old. My oncologist said it was as rare as seeing a penguin in the wild... wearing a top hat... and shoes... and a sparkly bowtie.",
      sectionTreatmentH: 'Treatment Tuesday. Festival Friday.',
      sectionTreatmentP: "After four rounds of immunotherapy, I started on targeted therapy — a few pills a day that allow me a quality of life I couldn't have imagined a year ago. I'm still here. Still showing up. Still wearing colors.",
      sectionLLSH: 'Why this foundation exists.',
      sectionLLSP1: "As a Community Outreach Volunteer with the Leukemia & Lymphoma Society, I've spent a year supporting Laura Diaz's Spanish Education Programs and sharing my story across San Diego County. In 2024 I ran as an LLS Visionaries of the Year candidate — a 10-week campaign that raised over $90,000 for blood cancer research.",
      sectionLLSP2: "But I noticed something, over and over: sorting through resources as a young adult with cancer was its own battle. Every patient I met was tired of clicking through sites that weren't built for us. Every family was drowning in PDFs and phone numbers.",
      sectionLLSP3: 'FIGHT4 is what I wish I had. A single, trustworthy place — vetted by young adults who lived through treatment, speaking the language we actually speak, pointing to the help that actually exists.',
      sectionTeamH: 'By the people, for the people.',
      sectionTeamP: 'FIGHT4 is built and vetted by young adults who have been through cancer treatment themselves. Every resource on this site was personally used or reviewed by someone who understands what it takes to use it.',
      signoff: 'Un abrazo,',
    },
    resources: {
      eyebrow: 'Resource Library',
      h1: 'The library is coming.',
      sub: "We're building a filterable, personally-reviewed library of cancer resources for young adults — by stage of treatment, age, location, and type of support. In the meantime, put your email below and we'll tell you the moment it's live.",
      placeholder: 'your@email.com',
      button: 'Notify me when it launches',
      thanks: "We'll email you the moment the library is live.",
      categoriesH: "What we're building",
      categories: [
        { t: 'Financial Aid', d: 'Grants, co-pay assistance, travel funds, and emergency cost coverage — filtered by what you actually qualify for.' },
        { t: 'Support Groups', d: 'YA-specific groups, peer matching, online communities, and in-person meetups — in English and Spanish.' },
        { t: 'Free Experiences', d: 'Retreats, camps, adventures, festivals, concerts, and trips for young adults with cancer.' },
        { t: 'Quick Guides', d: "Short, plain-language walkthroughs for each major milestone: just diagnosed, in treatment, in remission, and beyond." },
      ],
    },
    movement: {
      eyebrow: 'The Movement',
      wordmark: 'What do you fight 4?',
      lede: "#WhatDoYouFight4 is more than a hashtag. It's a call to action for anyone touched by cancer to share their story, their purpose, and what keeps them going.",
      body1: "For some, the fight is personal — battling illness, overcoming challenges, advocating for better resources. For others, it's about fighting for a loved one, for awareness, for a future where no one faces this alone.",
      body2: "We believe everyone has something worth fighting for. By sharing our stories we foster connection, break stigma, and remind each other that this journey doesn't have to be walked in silence.",
      cta: 'Join the conversation. Share your story. Be part of the movement.',
      ctaButton: 'Share on Instagram',
    },
    ask: {
      eyebrow: 'Ask F4',
      h1: 'Tell us where you are. We\'ll match you to what can actually help.',
      sub: "Instead of searching through dozens of sites, just tell us your situation — stage of treatment, age, where you live, what kind of help you need — and we'll surface the vetted resources that fit. No web scraping. No generic answers. Only what's been personally reviewed by young adults who've been there.",
      comingSoon: 'Launching Fall 2026',
      demoLabel: 'What this will look like',
      demoUser: "I just got diagnosed with lymphoma. I'm 24, in Boston, and I need help with medical bills.",
      demoAssistant: "I'm sorry you're here, but I'm glad you found us. For your situation I'd start with three resources — all personally vetted:\n\n1. The Leukemia & Lymphoma Society Co-Pay Assistance Program (covers insurance co-pays and premiums for lymphoma patients, Massachusetts residents eligible).\n\n2. Cancer and Careers — specifically their financial planning resources for young adults in active treatment.\n\n3. The Samfund — grants for young adults with cancer facing financial crisis, typically $500–$4,000 per grant.\n\nWant me to go deeper on any of these, or pull up emotional support and community resources too?",
    },
    common: {
      readStory: "Read Natalia's story",
      backHome: '← Back to home',
    },
  },
  es: {
    nav: {
      tagline: 'Por la gente, para la gente.',
      resources: 'Recursos',
      quickGuides: 'Guías rápidas',
      story: 'Nuestra historia',
      movement: '#PorQuéLuchas',
      ask: 'Pregúntale a F4',
    },
    trustBar: {
      verified: 'Cada recurso verificado personalmente por jóvenes adultos que han estado en tratamiento',
      updated: 'Actualizado mensualmente',
      disclaimer: 'Aviso médico',
    },
    hero: {
      eyebrow: 'La Fundación FIGHT4',
      lede: 'Por la gente, para la gente.',
      h1Line1: 'Por jóvenes',
      h1Line1Mark: 'con cáncer.',
      h1Line2: 'Para jóvenes',
      h1Line2Mark: 'con cáncer.',
      sub: 'Ayuda financiera. Grupos de apoyo. Experiencias gratuitas. Conexiones a las organizaciones que sí pueden ayudar. Cada recurso en FIGHT4 es revisado personalmente por jóvenes adultos que pasaron por tratamiento — porque nosotros mismos los hemos usado.',
      ctaPrimary: 'Encuentra recursos para ti',
      ctaSecondary: 'Explora la biblioteca',
    },
    stats: {
      raised: { num: '$90K', label: 'Recaudados para investigación del cáncer de sangre vía LLS' },
      partners: { num: '5', label: 'Organizaciones aliadas en el espacio del cáncer en jóvenes' },
      vetted: { num: '100%', label: 'Recursos verificados por jóvenes que han estado ahí' },
    },
    founder: {
      tag: 'Fundadora',
      quote: '"Durante siete meses, los doctores pensaron que tenía meningitis. Cuando por fin me diagnosticaron — Linfoma No-Hodgkin de la Zona Marginal del Bazo, un mes antes de cumplir 23 años — buscar recursos en tratamiento fue su propio tipo de agotamiento. FIGHT4 es lo que desearía haber tenido entonces."',
      name: 'Natalia Menéndez',
      role: 'Fundadora · Sobreviviente de SMZL · Candidata LLS Visionaries of the Year · Revisa cada recurso personalmente',
      closing: 'Por la gente, para la gente.',
    },
    partners: {
      label: 'Conectados con las organizaciones que los jóvenes con cáncer realmente necesitan',
      disclaimer: 'Logotipos mostrados con permiso. Las organizaciones listadas no son patrocinadores formales de la Fundación FIGHT4.',
    },
    pillars: {
      title: 'Cuatro pilares, una misión: nadie lucha solo.',
      subtitle: 'Nuestro marco para lo que cubrimos, lo que verificamos y cómo apoyamos a jóvenes adultos en todo el mundo.',
      items: [
        { num: '01 / NAVEGAR LA INFORMACIÓN', title: 'Cortar el ruido', body: 'Revisar los recursos disponibles puede ser abrumador. Nosotros hacemos el trabajo de encontrar, resumir y organizar — para que tú no tengas que hacerlo.' },
        { num: '02 / EDUCACIÓN', title: 'Romper el estigma', body: 'Las conversaciones sobre temas tabú o difíciles son cómo construimos entendimiento, comunidad y valentía en los jóvenes que enfrentan el cáncer.' },
        { num: '03 / CENTRO DE RECURSOS', title: 'Una biblioteca centralizada', body: 'Ayuda financiera, grupos de apoyo, experiencias gratuitas, conexiones con organizaciones importantes — todo en un lugar, filtrable por tu situación.' },
        { num: '04 / RED GLOBAL', title: 'No importa dónde estés', body: 'El cáncer no se detiene en las fronteras. Nuestra biblioteca se cura con mentalidad internacional, conectando jóvenes con recursos en todo el mundo.' },
      ],
    },
    disclaimer: {
      heading: 'Aviso médico.',
      body: 'FIGHT4 resume información disponible públicamente de fuentes confiables como hospitales, proveedores de salud y organizaciones sin fines de lucro. Aunque buscamos precisión, verifica los detalles con profesionales de la salud. No cubrimos todos los recursos disponibles y no respaldamos organizaciones específicas. Los enlaces externos son solo por conveniencia. Este recurso no sustituye la atención médica profesional — siempre consulta a tu equipo médico y grupos de apoyo para consejo personalizado.',
    },
    footer: {
      brandLine1: 'Por la gente,',
      brandLine2: 'para la gente.',
      tagline: 'Fundación FIGHT4 — construida por jóvenes con cáncer, para jóvenes con cáncer. Nadie lucha solo.',
      colResources: 'Recursos',
      colFoundation: 'Fundación',
      colTrust: 'Confianza',
      copyright: '© 2026 Fundación FIGHT4',
      reviewedBy: 'Cada recurso revisado personalmente por Natalia Menéndez, sobreviviente de linfoma.',
    },
    about: {
      eyebrow: 'Nuestra historia',
      h1: 'Durante siete meses, los doctores pensaron que tenía meningitis.',
      lede: 'Al final de seis punciones lumbares, múltiples biopsias y visitas a urgencias que preferiría olvidar — por fin me diagnosticaron con Linfoma No-Hodgkin de la Zona Marginal del Bazo, un mes antes de cumplir 23 años.',
      body1: 'Estaba en riesgo de sufrir un ataque cerebral, tuve síntomas cognitivos severos, migrañas debilitantes, y la mitad de mi cuerpo se entumecía. Durante meses vi especialistas en enfermedades infecciosas, neurólogos y oncólogos que no podían encontrarlo.',
      body2: 'El cáncer se había extendido a mi sistema nervioso central. La edad media de diagnóstico para SMZL es de 65–70 años. Mi oncóloga dijo que era tan raro como ver un pingüino en la naturaleza... con sombrero de copa... zapatos... y un moño brillante.',
      sectionTreatmentH: 'Martes de tratamiento. Viernes de festival.',
      sectionTreatmentP: 'Después de cuatro rondas de inmunoterapia, empecé terapia dirigida — unas cuantas pastillas al día que me permiten una calidad de vida que no podía haber imaginado hace un año. Sigo aquí. Sigo apareciendo. Sigo usando colores.',
      sectionLLSH: 'Por qué existe esta fundación.',
      sectionLLSP1: 'Como Voluntaria Comunitaria de la Sociedad de Leucemia y Linfoma, llevo un año apoyando los Programas de Educación en Español de Laura Diaz y compartiendo mi historia por todo San Diego. En 2024 fui candidata en la campaña Visionarios del Año de LLS — 10 semanas en las que recaudamos más de $90,000 para investigación del cáncer de sangre.',
      sectionLLSP2: 'Pero noté algo, una y otra vez: buscar recursos como joven adulto con cáncer era su propia batalla. Cada paciente que conocí estaba cansado de clicar en sitios que no fueron hechos para nosotros. Cada familia se estaba ahogando en PDFs y números de teléfono.',
      sectionLLSP3: 'FIGHT4 es lo que desearía haber tenido. Un lugar único y confiable — verificado por jóvenes que vivieron el tratamiento, hablando el idioma que realmente hablamos, apuntando a la ayuda que sí existe.',
      sectionTeamH: 'Por la gente, para la gente.',
      sectionTeamP: 'FIGHT4 está construido y verificado por jóvenes adultos que han pasado por tratamiento de cáncer. Cada recurso en este sitio fue usado o revisado personalmente por alguien que entiende lo que toma usarlo.',
      signoff: 'Un abrazo,',
    },
    resources: {
      eyebrow: 'Biblioteca de recursos',
      h1: 'La biblioteca está en camino.',
      sub: 'Estamos construyendo una biblioteca filtrable, revisada personalmente, de recursos sobre cáncer para jóvenes adultos — por etapa de tratamiento, edad, ubicación y tipo de apoyo. Mientras tanto, pon tu correo abajo y te avisamos el momento en que esté lista.',
      placeholder: 'tu@correo.com',
      button: 'Avísame cuando salga',
      thanks: 'Te escribiremos el momento en que la biblioteca esté en vivo.',
      categoriesH: 'Lo que estamos construyendo',
      categories: [
        { t: 'Ayuda financiera', d: 'Becas, asistencia con co-pagos, fondos de viaje, y cobertura de costos de emergencia — filtrados por lo que realmente calificas.' },
        { t: 'Grupos de apoyo', d: 'Grupos específicos para jóvenes, emparejamiento entre pares, comunidades en línea y encuentros presenciales — en inglés y español.' },
        { t: 'Experiencias gratuitas', d: 'Retiros, campamentos, aventuras, festivales, conciertos y viajes para jóvenes adultos con cáncer.' },
        { t: 'Guías rápidas', d: 'Guías cortas y claras para cada etapa principal: recién diagnosticado, en tratamiento, en remisión, y más allá.' },
      ],
    },
    movement: {
      eyebrow: 'El Movimiento',
      wordmark: '¿Por qué luchas?',
      lede: '#PorQuéLuchas es más que un hashtag. Es un llamado a la acción para cualquiera tocado por el cáncer a compartir su historia, su propósito y lo que los mantiene adelante.',
      body1: 'Para algunos, la lucha es personal — enfrentando la enfermedad, superando retos, abogando por mejores recursos. Para otros, es luchar por un ser querido, por concientización, por un futuro donde nadie enfrente esto solo.',
      body2: 'Creemos que todos tienen algo por qué luchar. Al compartir nuestras historias fomentamos conexión, rompemos el estigma y nos recordamos que este camino no tiene que caminarse en silencio.',
      cta: 'Únete a la conversación. Comparte tu historia. Sé parte del movimiento.',
      ctaButton: 'Compartir en Instagram',
    },
    ask: {
      eyebrow: 'Pregúntale a F4',
      h1: 'Dinos dónde estás. Te conectamos con lo que sí puede ayudar.',
      sub: 'En lugar de buscar en docenas de sitios, solo cuéntanos tu situación — etapa del tratamiento, edad, dónde vives, qué tipo de ayuda necesitas — y te mostraremos los recursos verificados que encajan. Sin scraping web. Sin respuestas genéricas. Solo lo que ha sido revisado personalmente por jóvenes que han estado ahí.',
      comingSoon: 'Lanzamiento Otoño 2026',
      demoLabel: 'Así se verá',
      demoUser: 'Me acaban de diagnosticar con linfoma. Tengo 24 años, vivo en Boston y necesito ayuda con las cuentas médicas.',
      demoAssistant: 'Siento que estés aquí, pero me alegra que nos hayas encontrado. Para tu situación empezaría con tres recursos — todos verificados personalmente:\n\n1. Programa de Asistencia de Co-Pagos de LLS (cubre co-pagos y primas de seguro para pacientes con linfoma, residentes de Massachusetts elegibles).\n\n2. Cancer and Careers — específicamente sus recursos de planificación financiera para jóvenes en tratamiento activo.\n\n3. The Samfund — becas para jóvenes con cáncer enfrentando crisis financiera, típicamente $500–$4,000 por beca.\n\n¿Quieres que profundice en alguno, o también que saque recursos de apoyo emocional y comunidad?',
    },
    common: {
      readStory: 'Lee la historia de Natalia',
      backHome: '← Volver al inicio',
    },
  },
} as const;
